
server:
  port: ${port:9001}

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/data-model?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: admin
      password: 123456
      driverClassName:  com.mysql.jdbc.Driver
  jpa:
    show-sql: true
common
logging:
  level:
    org.springframework.security: DEBUG
  path: /var/logs 
  file: app.log

# 默认的profile为dev，其他环境CommonDefine通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar xxx.jar --spring.profiles.active=test
#   生产环境：java -jar xxx.jar --spring.profiles.active=prod
#spring:
#  profiles:
#    active: dev

##下面这一行务必不能少，区分不同配置，而且必须是三个字符"-"
#---
## 开发环境配置
#spring:
#  profiles: dev
#  datasource:
#      url: jdbc:mysql://192.168.1.247:3306/epension_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      username: root
#      password: Aa123456
#      driverClassName:  com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    org.springframework.security: DEBUG
#---
## 测试环境配置
#spring:
#  profiles: test
#  datasource:
#    url: jdbc:mysql://192.168.1.247:3306/epension_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: Aa123456
#    driverClassName:  com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
## LOGGING 
#logging:
#  path: /var/logs 
#  file: health-app-service.log
#
#---
## 生产环境配置
#spring:
#  profiles: prod
#  datasource:
#     url: jdbc:mysql://192.168.1.247:3306/epension_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#     username: root
#     password: Aa123456
#     driverClassName:  com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update



